# Generated by Django 5.2.10 on 2026-02-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_guest_count_venue_amenities_venue_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
