# Generated by Django 5.2.10 on 2026-02-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('organizer', 'Organizer'), ('owner', 'Owner')], default='user', max_length=20),
        ),
    ]
