# Generated by Django 6.0.1 on 2026-02-16 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toiapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='super_user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='super_user',
            name='build_phone',
        ),
        migrations.RemoveField(
            model_name='super_user',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='super_user',
            name='password',
        ),
    ]
